from __future__ import annotations

from typing import Any, Mapping, Optional, Protocol


class SourceRepositoryProtocol(Protocol):
    def upsert_source(self, source: Mapping[str, Any]) -> str: ...


class RssFeedRepositoryProtocol(Protocol):
    def upsert_feed(self, source_id: str, feed: Mapping[str, Any]) -> str: ...


class ArticleRepositoryProtocol(Protocol):
    def get_by_dedupe_hash(self, dedupe_hash: str) -> Optional[dict[str, Any]]: ...
    def create_article(self, source_id: str, rss_feed_id: str, ingestion_run_id: str, article: Mapping[str, Any]) -> str: ...
    def mark_duplicate_seen(self, article_id: str, ingestion_run_id: str) -> None: ...
    def list_candidates_for_analysis(self, limit: int) -> list[dict[str, Any]]: ...
    def list_news_collector_candidates(self, limit: int) -> list[dict[str, Any]]: ...
    def update_article_analysis(self, article_id: str, analysis: Mapping[str, Any]) -> None: ...
    def list_candidates_for_recommendation(self, limit: int) -> list[dict[str, Any]]: ...
    def update_recommendation(self, article_id: str, recommendation: Mapping[str, Any]) -> None: ...
    def list_review_candidates(self, limit: int, min_score: float) -> list[dict[str, Any]]: ...
    def list_articles_for_selection_review(self, limit: int, min_final_score: float) -> list[dict[str, Any]]: ...
    def get_article_by_id(self, article_id: str) -> Optional[dict[str, Any]]: ...
    def list_confirmed_articles_without_candidate(self, limit: int) -> list[dict[str, Any]]: ...
    def update_review_status(self, article_id: str, review_status: str) -> None: ...
    def update_selection_status(self, article_id: str, selection_status: str) -> None: ...


class ArticleReviewRepositoryProtocol(Protocol):
    def create_review(self, review: Mapping[str, Any]) -> str: ...
    def find_latest_review(self, article_id: str) -> Optional[dict[str, Any]]: ...
    def has_confirm_review(self, article_id: str) -> bool: ...
    def find_latest_confirm_review(self, article_id: str) -> Optional[dict[str, Any]]: ...


class GeneratedContentRepositoryProtocol(Protocol):
    def create_generated_content(self, content: Mapping[str, Any]) -> str: ...
    def find_by_article_and_type(self, article_id: str, content_type: str) -> Optional[dict[str, Any]]: ...


class IngestionRunRepositoryProtocol(Protocol):
    def start_run(self, source_id: str, rss_feed_id: str, feed_url_snapshot: str, triggered_by: str, request_payload: Mapping[str, Any]) -> str: ...
    def complete_run(
        self,
        ingestion_run_id: str,
        *,
        status: str,
        items_fetched: int,
        items_saved: int,
        items_duplicate: int,
        items_failed: int,
        result_payload: Mapping[str, Any],
        error_message: str = "",
    ) -> None: ...


class SystemConfigRepositoryProtocol(Protocol):
    def get_value(self, config_key: str, default: Any = None) -> Any: ...
    def set_value(self, config_key: str, config_value: Any) -> None: ...


class ReviewerRepositoryProtocol(Protocol):
    def upsert_reviewer(self, reviewer: Mapping[str, Any]) -> str: ...
    def list_active_reviewers(self) -> list[dict[str, Any]]: ...
    def get_by_reviewer_code(self, reviewer_code: str) -> Optional[dict[str, Any]]: ...


class TelegramReviewDispatchRepositoryProtocol(Protocol):
    def create_dispatch(self, dispatch: Mapping[str, Any]) -> str: ...
    def mark_dispatch_sent(self, dispatch_id: str, payload: Mapping[str, Any]) -> None: ...
    def mark_dispatch_failed(self, dispatch_id: str, error_message: str, payload: Mapping[str, Any]) -> None: ...
    def mark_dispatch_acted(self, dispatch_id: str, payload: Mapping[str, Any]) -> None: ...
    def get_dispatch_by_message(self, telegram_chat_id: str, telegram_message_id: int) -> Optional[dict[str, Any]]: ...
